bower install datatables --save
bower install daterangepicker --save
bower install flot --save
bower install fullcalendar --save
bower install iCheck --save
bower install input-mask --save
bower install ionslider --save
bower install jqueryKnob --save
bower install jvectormap --save
bower install misc --save
bower install morris --save
bower install slimScroll --save
bower install sparkline --save
bower install timepicker --save
